// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	DATABASE_ID: string;
	ACCOUNT_ID: string;
	API_KEY: string;
	GROK_KEY: any;
}
